insert into t_permission(id, name, description) VALUES (1,'USER_VIEW', 'View Users' );
insert into t_permission(id, name, description) VALUES (2,'USER_CREATE', 'Create User Record' );
insert into t_permission(id, name, description) VALUES (3,'USER_UPDATE', 'Update User Record' );
insert into t_permission(id, name, description) VALUES (4,'USER_DELETE', 'Delete User Record' );
insert into t_permission(id, name, description) VALUES (5,'ROLE_VIEW', 'View Role' );
insert into t_permission(id, name, description) VALUES (6,'ROLE_CREATE', 'Create Role' );
insert into t_permission(id, name, description) VALUES (7,'ROLE_UPDATE', 'Update Role' );
insert into t_permission(id, name, description) VALUES (8,'ROLE_DELETE', 'Delete Role' );
insert into t_permission(id, name, description) VALUES (9,'USER_GROUP_VIEW', 'View User Groups' );
insert into t_permission(id, name, description) VALUES (10,'USER_GROUP_CREATE', 'Create User Groups' );
insert into t_permission(id, name, description) VALUES (11,'USER_GROUP_UPDATE', 'Update User Groups' );
insert into t_permission(id, name, description) VALUES (12,'USER_GROUP_DELETE', 'Delete User Groups' );
